version: '3.7'

services:
  frontend:
    build:
      context: probetspp_front/
    env_file:
      - .env.prod
    volumes:
      - frontapp:/app/build
  app:
    build:
      context: .
      dockerfile: Dockerfile.pi
    #ports:
    #  - "8000:8000"
    volumes:
      - .:/opt/app
      - static:/tmp/probetspp/static
    env_file:
      - .env.prod
    #environment:
    #  - DEBUG=1
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 8081:8081
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/tmp/probetspp/static
      - frontapp:/usr/share/nginx/html
    depends_on:
      - app
volumes:
  .:
  static:
  frontapp:
