services:
  postgres:
    image: postgres:13
    command: postgres -c log_statement=all
    environment:
      POSTGRES_DB: probetspp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    #ports:
    #  - "8000:8000"
    volumes:
      - .:/opt/app
      - static:/tmp/probetspp/static
    env_file:
      - .env.prod
    #environment:
    #  - DEBUG=1
    depends_on:
      postgres:
        condition: service_healthy
  # frontend:
  #   build:
  #     context: probetspp_front/
  #   env_file:
  #     - .env.prod
  #   volumes:
  #     - frontapp:/app/build
  #   depends_on:
  #     - app
  nginx:
    image: nginx:1.29.4
    ports:
      - 80:80
      - 8081:8081
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/tmp/probetspp/static
      # - frontapp:/usr/share/nginx/html
    depends_on:
      - app
volumes:
  .:
  static:
  postgres_data:
  # frontapp:
